# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift_video_camera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'OpenCV'
  # Pods for swift_video_camera

end
